### ISSUE TITLE
Fix page

### ISSUE THREAD

**Issue by rhvsingh** [rhvsingh/website_repo_1#12]
Fix duplicate sections.
Fix contact form
Fix animation image and other bugs.

**Comment by then00bprogrammer** [comment]
hi i can fix this..assign me

**Comment by rhvsingh** [comment]
> hi i can fix this..assign me

Go ahead 👍

**Comment by aniket2003** [comment]
rhvsingh can you assign me with this i can fix this

**Comment by then00bprogrammer** [comment]
hi i fixed the duplicate section and animation image but can't seem to figure out what do you mean by fix contact form?

**Comment by then00bprogrammer** [comment]
hi @rhvsingh as i can see you've made quite a few changes to the repository so should i change my according to that?

**Comment by rhvsingh** [comment]
> hi @rhvsingh as i can see you've made quite a few changes to the repository so should i change my according to that?

Yes sir.

**Comment by then00bprogrammer** [comment]
the website looks fine now, what do you exactly want me to now that you've fixed all the issues yourself?

**Comment by rhvsingh** [comment]
> the website looks fine now, what do you exactly want me to now that you've fixed all the issues yourself? @rhvsingh

The contact button is not working, not opening the form modal.
The image slider is not working now.
Remove the underline from the navigation LOGO.
Remove extra space between the "navigation" section and the "connect with us"  section in the footer.
